### PR TITLE
Enable `expr` bindings with lua res

### PR DESCRIPTION
**Pull request by LionC**
Relates to #12

### CODE REVIEW

**Comment by Corey-Keller** [comment]
@LionC FYI: This change broke support for inline functions (or at least causes issues with it) . 

Take a mapping like this:

```
require('nest').applyKeymaps { {'<leader>f',{                                                                                                                                                               
    {'v', function()                                                                                                                                                                                    
        tel_builtin.find_files{                                                                                                                                                                     
            cwd = vim.fn.stdpath('config'),                                                                                                                                                     
            prompt_title = "Neovim Config",                                                                                                                                                     
        }                                                                                                                                                                            
    end }
...
```

Prior to the change (when using `'<Cmd>lua require("nest").functions[' .. registerFunction(second) .. ']()<CR>'` ) there were no issues, but now when the map is ran it gives `E5108: Error executing lua [string ":lua"]:1: Expected lua string` before working as expected (with a delay)

**Comment by Corey-Keller** [comment]
@LionC The problem lies in the `return vim.api.nvim_replace_termcodes(keys, true, true, true)` line of `_callRhsFn`

`nvim_replace_termcodes() expects a string, and not a function. If I'm understanding the code (and the issue that necessitates it) correctly, then you'd only want to call `_callRhsFn()` if the function was a string (which it's not... it's a function... right?).

**Comment by LionC** [comment]
Hey Corey. Good catch - final testing before 1.1 is still pending, but it seems you did that for me, thanks :-)

I think the problem here is that "normal" lua bindings usually return nil, which will trip up the termcodes escaper. It should simply not be called for non expr bindings, I will add a solution for that later today :-)

**Comment by LionC** [comment]
@Corey-Keller Fixed in the #10 branch :-)

**Comment by Corey-Keller** [comment]
@LionC Thanks again for all your quick work! Works flawlessly now in my (admittedly brief and limited) testing!

**Pull request merged**
