### PR TITLE
✨ Add lua function rhs support

### LINKED ISSUE #5: Allow arbitrary `lua` functions for right side keymap values

### PR DESCRIPTION
**Pull request by LionC**
Closes #5

### CODE REVIEW

**Comment by Corey-Keller** [comment]
Personally I don't think you should remove the ldoc just because "no one else" uses it. I personally find the usage of a standard documentation/commenting style to be a good idea, and the information that you removed in 19731b2 is useful info for someone working with the code, or even just referring back to it in the future.

**Comment by Corey-Keller** [comment]
Am I correct in my understanding that this initial version only takes the name of a function as a value? 

Do you know yet how you plan to handle functions with arguments?

Also, I just wanted to say I'm impressed at how quickly you have began to implement this! Thanks!

**Comment by LionC** [comment]
> Am I correct in my understanding that this initial version only takes the name of a function as a value?
> 
> Do you know yet how you plan to handle functions with arguments?
> 
> Also, I just wanted to say I'm impressed at how quickly you have began to implement this! Thanks!

It takes a function as a value - using its "name" (meaning a local reference to it) is one way, but in the end it is just a lua value that is a function.

I would not know what arguments to pass for now - the lua function can get pretty much all context it needs from nvim APIs, I cannot think of anything `nest` specific I would want to pass.

**Comment by LionC** [comment]
> Personally I don't think you should remove the ldoc just because "no one else" uses it. I personally find the usage of a standard documentation/commenting style to be a good idea, and the information that you removed in [19731b2](https://github.com/LionC/nest.nvim/commit/19731b23d61b382fa250255c70e84112ea401082) is useful info for someone working with the code, or even just referring back to it in the future.

The problem with LuaDoc is that it actually makes it a bit harder to read the comments while not being supported by the recommended Lua Language server. I will add comments back, but choose a format tuned for readability instead.

**Comment by Corey-Keller** [comment]
Perhaps this example will clear up what I mean when I mention arguments:
```
local nest = require('nest')

local function people(alice, bob)
	return print("The people are " .. alice .. " and " .. bob)
end

local function people_stat()
	return print("The people are frank and carl")
end

nest.applyKeymaps { {'<leader>t',{
	{'m', people_stat},
	{'n', people('jim', 'bill')},
}}}
```

It's the examples like `<leader>tn` above that I'm wondering about. How do I pass the `alice` and `bob` variables to the `people` function?

**Pull request merged**
